@startuml

package Core{
	class Basic extends V{
		+package:string
		+dateCreated:datetime
		+dateChanged:datetime
	}
	class	Link extends E{
		+type
	}
}

package Storage{

	package Law{

		abstract class Body extends Basic{
			+langs:string[]
			+contacts:Contact[]
		}

		class Legal extends Body{
			+nameShort
			+nameFull
			+stockLinks
		}
		class Person extends Body{
			+name:String
			+familyName:string
			+dateBirth
			+dateDeath
		}
		class Contact extends Basic{
			+contactName
			+reactionInterval
		}

	}

	package Data{
		class DataItem extends Basic
		class DataItemRevision extends DataItem
	}

}

package Service {
	Client -u-|> Legal
}

@enduml
